### ISSUE TITLE
Depth camera not working in some countries (if Float numbers in 1,4523 format instead 1.4532)

### ISSUE THREAD

**Issue by radoslawsz** [SonySemiconductorSolutions/tof-ar-samples-basic#1]
TofArToManager.cs in line 2755 generate error in  some countries 
because float.Parse in C# use national float formats and cause runtime error if it is wrong f.e:
in Poland we use 1,4523 instead 1.4523 .

Fix:
In function ParseSettingsString change all 8 lines like this : 
float fxColor = float.Parse(pasteSetting[0]
to:
float fxColor = float.Parse(pasteSetting[0], System.Globalization.CultureInfo.InvariantCulture);

I find same problem in TofArToManager.cs  in lines started from 2821 :
R.a = float.Parse(pasteSetting[8]);
to 
R.a = float.Parse(pasteSetting[8], System.Globalization.CultureInfo.InvariantCulture);
and next 12 occurences 
 
  
I finally find that this error is in file from "ToF AR SDK Basic"  not this sample but:

**Comment by HirotakaGoto** [comment]
Hello radoslawsz,

Thank you very much for your information !
We found the same problem when we also switched the region of the smartphone.
And we have confirmed that your changes fix the problem.
TofArTofManager.cs is included in the ToF AR SDK, so we will try to release a fixed version.
We apologize that the release of new ToF AR SDK will take time.

ToF AR Team

**Comment by tofar-integ01** [comment]
Hello radoslawsz,

We released the fixed ToF AR v1.3.1 and Apps on May 29th.
Make sure to keep your ToF AR toolkit up to date!

ToF AR Team
